# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Joshwin Greene
tagline:             'Developer/Designer @ ScholarDev Apps'
description:         'As you see, this site is a <span style="color:white;">work in progress</span>. However, in the meantime, feel free to follow me on Twitter <a href="https://twitter.com/josh_w_g" target="_blank">@josh_w_g</a> or on <a href="https://plus.google.com/u/0/+JoshwinGreene" target="_blank">Google+</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
